# Generated by Django 2.2.7 on 2019-11-30 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=32, unique=True)),
                ('platform', models.CharField(choices=[('I', 'iOS'), ('A', 'Android')], max_length=1)),
                ('bundle_id', models.CharField(max_length=255, unique=True)),
                ('fb_app_id', models.CharField(max_length=32)),
                ('fb_client_token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=64, unique=True)),
                ('advertiser_id', models.CharField(max_length=64, null=True)),
                ('fb_user_id', models.CharField(max_length=64, null=True)),
                ('bundle_short_version', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('sum', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('is_sandbox', models.SmallIntegerField(default=0)),
                ('is_valid', models.SmallIntegerField(default=0)),
                ('is_logged', models.SmallIntegerField(default=0)),
                ('ext_info', models.TextField()),
                ('request_body', models.TextField()),
                ('log_timestamp', models.IntegerField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divineog.App')),
            ],
        ),
    ]
