# Generated by Django 3.0 on 2019-12-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackbook', '0003_auto_20191216_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='transaction_date',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
