# Generated by Django 3.0 on 2020-09-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackbook', '0004_purchase_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(max_length=64),
        ),
    ]
