# Generated by Django 3.0 on 2020-09-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackbook', '0005_auto_20200901_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='ads_txt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='privacy_policy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='terms_of_use',
            field=models.TextField(null=True),
        ),
    ]
